import { existsSync, promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { cwd } from "node:process";
import { rimraf } from "rimraf";
import {
  type Registry,
  registryItemSchema,
  type registryItemTypeSchema,
  registrySchema,
} from "shadcn/schema";
import { Project, ScriptKind, SyntaxKind } from "ts-morph";
import type { z } from "zod";
import { type RegistryBase, registries } from "../registry";
import { STYLES } from "../registry/styles";
import { fixImport } from "./fix-imports.mts";

const REGISTRY_PATH = path.join(process.cwd(), "public/r");

const REGISTRY_INDEX_WHITELIST: z.infer<typeof registryItemTypeSchema>[] = [
  "registry:ui",
  "registry:lib",
  "registry:hook",
  "registry:theme",
  "registry:block",
  "registry:example",
  "registry:component",
  "registry:internal",
  "registry:style",
];

// Define bases to build
const BASES: RegistryBase[] = ["radix", "base"];

// Map styles for compatibility
const styles = STYLES.map((s) => ({ name: s.name, label: s.title }));

const project = new Project({
  compilerOptions: {},
});

async function createTempSourceFile(filename: string) {
  const dir = await fs.mkdtemp(path.join(tmpdir(), "shadcn-"));
  return path.join(dir, filename);
}

// ----------------------------------------------------------------------------
// Build __registry__/index.tsx.
// ----------------------------------------------------------------------------
async function buildRegistry() {
  let index = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, Record<string, any>> = {
`;

  for (const baseName of BASES) {
    const registry = registries[baseName];

    index += `  "${baseName}": {`;

    for (const style of styles) {
      index += `
    "${style.name}": {`;

      // Build style index.
      for (const item of registry.items) {
        const resolveFiles = item.files?.map(
          (file) =>
            `registry/bases/${baseName}/${
              typeof file === "string" ? file : file.path
            }`,
        );
        if (!resolveFiles) {
          continue;
        }

        const type = item.type.split(":")[1];
        let sourceFilename = "";

        // biome-ignore lint/suspicious/noExplicitAny: chunks can contain various types from AST parsing
        let chunks: any = [];
        if (item.type === "registry:block") {
          const file = resolveFiles[0];
          const filename = path.basename(file);
          let raw: string;
          try {
            raw = await fs.readFile(file, "utf8");
          } catch (_error) {
            continue;
          }
          const tempFile = await createTempSourceFile(filename);
          const sourceFile = project.createSourceFile(tempFile, raw, {
            scriptKind: ScriptKind.TSX,
          });

          const description = sourceFile
            .getVariableDeclaration("description")
            ?.getInitializerOrThrow()
            .asKindOrThrow(SyntaxKind.StringLiteral)
            .getLiteralValue();

          item.description = description ?? "";

          // Find all imports.
          const imports = new Map<
            string,
            {
              module: string;
              text: string;
              isDefault?: boolean;
            }
          >();
          for (const node of sourceFile.getImportDeclarations()) {
            const module = node.getModuleSpecifier().getLiteralValue();
            for (const importItem of node.getNamedImports()) {
              imports.set(importItem.getText(), {
                module,
                text: node.getText(),
              });
            }

            const defaultImport = node.getDefaultImport();
            if (defaultImport) {
              imports.set(defaultImport.getText(), {
                module,
                text: defaultImport.getText(),
                isDefault: true,
              });
            }
          }

          // Find all opening tags with x-chunk attribute.
          const components = sourceFile
            .getDescendantsOfKind(SyntaxKind.JsxOpeningElement)
            .filter((node) => {
              return node.getAttribute("x-chunk") !== undefined;
            });

          chunks = await Promise.all(
            components.map(async (component, chunkIndex) => {
              const chunkName = `${item.name}-chunk-${chunkIndex}`;

              // Get the value of x-chunk attribute.
              const attr = component
                .getAttributeOrThrow("x-chunk")
                .asKindOrThrow(SyntaxKind.JsxAttribute);

              const chunkDescription = attr
                .getInitializerOrThrow()
                .asKindOrThrow(SyntaxKind.StringLiteral)
                .getLiteralValue();

              // Delete the x-chunk attribute.
              attr.remove();

              // Add a new attribute to the component.
              component.addAttribute({
                name: "x-chunk",
                initializer: `"${chunkName}"`,
              });

              // Get the value of x-chunk-container attribute.
              const containerAttr = component
                .getAttribute("x-chunk-container")
                ?.asKindOrThrow(SyntaxKind.JsxAttribute);

              const containerClassName = containerAttr
                ?.getInitializer()
                ?.asKindOrThrow(SyntaxKind.StringLiteral)
                .getLiteralValue();

              containerAttr?.remove();

              const parentJsxElement = component.getParentIfKindOrThrow(
                SyntaxKind.JsxElement,
              );

              // Find all opening tags on component.
              const children = parentJsxElement
                .getDescendantsOfKind(SyntaxKind.JsxOpeningElement)
                .map((node) => {
                  return node.getTagNameNode().getText();
                })
                .concat(
                  parentJsxElement
                    .getDescendantsOfKind(SyntaxKind.JsxSelfClosingElement)
                    .map((node) => {
                      return node.getTagNameNode().getText();
                    }),
                );

              const componentImports = new Map<
                string,
                string | string[] | Set<string>
              >();
              for (const child of children) {
                const importLine = imports.get(child);
                if (importLine) {
                  const existingImports =
                    componentImports.get(importLine.module) || [];

                  const newImports = importLine.isDefault
                    ? importLine.text
                    : new Set([...existingImports, child]);

                  componentImports.set(
                    importLine.module,
                    importLine?.isDefault ? newImports : Array.from(newImports),
                  );
                }
              }

              const componentImportLines = Array.from(
                componentImports.keys(),
              ).map((key) => {
                const values = componentImports.get(key);
                const specifier = Array.isArray(values)
                  ? `{${values.join(",")}}`
                  : values;

                return `import ${specifier} from "${key}"`;
              });

              const code = `
            'use client'

            ${componentImportLines.join("\n")}

            export default function Component() {
              return (${parentJsxElement.getText()})
            }`;

              const targetFile = file.replace(item.name, `${chunkName}`);
              const targetFilePath = path.join(
                cwd(),
                `registry/bases/${baseName}/${type}/${chunkName}.tsx`,
              );

              // Write component file.
              rimraf.sync(targetFilePath);
              await fs.writeFile(targetFilePath, code, "utf8");

              return {
                name: chunkName,
                description: chunkDescription,
                component: `React.lazy(() => import("@/registry/bases/${baseName}/${type}/${chunkName}")),`,
                file: targetFile,
                container: {
                  className: containerClassName,
                },
              };
            }),
          );

          // // Write the source file for blocks only.
          sourceFilename = `__registry__/${baseName}/${style.name}/${type}/${item.name}.tsx`;

          if (item.files) {
            const files = item.files.map((file) =>
              typeof file === "string"
                ? { type: "registry:page", path: file }
                : file,
            );
            if (files?.length) {
              sourceFilename = `__registry__/${baseName}/${style.name}/${files[0].path}`;
            }
          }

          const sourcePath = path.join(process.cwd(), sourceFilename);
          if (!existsSync(sourcePath)) {
            await fs.mkdir(sourcePath, { recursive: true });
          }

          rimraf.sync(sourcePath);
          await fs.writeFile(sourcePath, sourceFile.getText());
        }

        let componentPath = `@/registry/bases/${baseName}/${type}/${item.name}`;

        if (item.files) {
          const files = item.files.map((file) =>
            typeof file === "string"
              ? { type: "registry:page", path: file }
              : file,
          );
          if (files?.length) {
            componentPath = `@/registry/bases/${baseName}/${files[0].path}`;
          }
        }

        // Skip component generation for metadata-only entries
        const shouldGenerateComponent =
          item.files &&
          item.files.length > 0 &&
          !["index", "style"].includes(item.name);

        index += `
      "${item.name}": {
        name: "${item.name}",
        description: "${item.description ?? ""}",
        type: "${item.type}",
        registryDependencies: ${JSON.stringify(item.registryDependencies)},
        files: [${item.files?.map((file) => {
          const filePath = `registry/bases/${baseName}/${
            typeof file === "string" ? file : file.path
          }`;
          const resolvedFilePath = path.resolve(filePath);
          return typeof file === "string"
            ? `"${resolvedFilePath}"`
            : `{
          path: "${filePath}",
          type: "${file.type}",
          target: "${file.target ?? ""}"
        }`;
        })}],${
          shouldGenerateComponent
            ? `
        component: React.lazy(() => import("${componentPath}")),`
            : ""
        }
        source: "${sourceFilename}",
        chunks: [${chunks.map(
          (chunk) => `{
          name: "${chunk.name}",
          description: "${chunk.description ?? "No description"}",
          component: ${chunk.component}
          file: "${chunk.file}",
          container: {
            className: "${chunk.container.className}"
          }
        }`,
        )}]
      },`;
      }

      index += `
    },`;
    }

    index += `
  },`;
  }

  index += `
}
`;

  // Write style index.
  rimraf.sync(path.join(process.cwd(), "__registry__/index.tsx"));
  await fs.writeFile(path.join(process.cwd(), "__registry__/index.tsx"), index);
}

// ----------------------------------------------------------------------------
// Build registry/index.json and registry/registry.json for each base.
// ----------------------------------------------------------------------------
async function buildRegistryJson() {
  for (const baseName of BASES) {
    const registry = registries[baseName];

    // ----------------------------------------------------------------------------
    // Build registry/index.json (UI components only).
    // ----------------------------------------------------------------------------
    const uiItems = registry.items
      .filter((item) => ["registry:ui"].includes(item.type))
      .map((item) => {
        return {
          ...item,
          files: item.files?.map((_file) => {
            const file =
              typeof _file === "string"
                ? {
                    path: _file,
                    type: item.type,
                  }
                : _file;

            return file;
          }),
        };
      });
    const indexJson = JSON.stringify(uiItems, null, 2);
    rimraf.sync(path.join(REGISTRY_PATH, `${baseName}-index.json`));
    await fs.writeFile(
      path.join(REGISTRY_PATH, `${baseName}-index.json`),
      indexJson,
      "utf8",
    );

    // ----------------------------------------------------------------------------
    // Build registry/registry.json (full registry object).
    // ----------------------------------------------------------------------------
    const allItems = registry.items
      .filter((item) => REGISTRY_INDEX_WHITELIST.includes(item.type))
      .filter((item) => item.name !== "index") // Skip index item
      .map((item) => {
        return {
          ...item,
          files: item.files?.map((_file) => {
            const file =
              typeof _file === "string"
                ? {
                    path: _file,
                    type: item.type,
                  }
                : _file;

            return file;
          }),
        };
      });
    const fullRegistry = {
      name: registry.name,
      homepage: registry.homepage,
      items: allItems,
    };
    const registryJson = JSON.stringify(fullRegistry, null, 2);
    rimraf.sync(path.join(REGISTRY_PATH, `${baseName}-registry.json`));
    await fs.writeFile(
      path.join(REGISTRY_PATH, `${baseName}-registry.json`),
      registryJson,
      "utf8",
    );
  }
}

// ----------------------------------------------------------------------------
// Build registry/[name].json for each base.
// ----------------------------------------------------------------------------
async function buildStyles() {
  for (const baseName of BASES) {
    const registry = registries[baseName];

    // biome-ignore lint/correctness/noUnusedVariables: style will be used when multi-style support is implemented
    for (const style of styles) {
      for (const item of registry.items) {
        if (!REGISTRY_INDEX_WHITELIST.includes(item.type)) {
          continue;
        }

        // Skip "index" item to avoid overwriting the UI component listing
        if (item.name === "index") {
          continue;
        }

        // biome-ignore lint/suspicious/noExplicitAny: files array can contain various registry item types
        let files: any[] = [];
        if (item.files) {
          files = await Promise.all(
            item.files.map(async (_file) => {
              const file =
                typeof _file === "string"
                  ? {
                      path: _file,
                      type: item.type,
                      content: "",
                      target: "",
                    }
                  : _file;

              let content: string;
              try {
                content = await fs.readFile(
                  path.join(
                    process.cwd(),
                    "registry",
                    "bases",
                    baseName,
                    file.path,
                  ),
                  "utf8",
                );

                // Only fix imports for v0- blocks.
                if (item.name.startsWith("v0-")) {
                  content = fixImport(content);
                }
              } catch (_error) {
                return;
              }

              const tempFile = await createTempSourceFile(file.path);
              const sourceFile = project.createSourceFile(tempFile, content, {
                scriptKind: ScriptKind.TSX,
              });

              sourceFile.getVariableDeclaration("iframeHeight")?.remove();
              sourceFile.getVariableDeclaration("containerClassName")?.remove();
              sourceFile.getVariableDeclaration("description")?.remove();

              let target = file.target || "";

              if ((!target || target === "") && item.name.startsWith("v0-")) {
                const fileName = file.path.split("/").pop();
                if (
                  file.type === "registry:block" ||
                  file.type === "registry:component" ||
                  file.type === "registry:example"
                ) {
                  target = `components/${fileName}`;
                }

                if (file.type === "registry:ui") {
                  target = `components/ui/${fileName}`;
                }

                if (file.type === "registry:hook") {
                  target = `hooks/${fileName}`;
                }

                if (file.type === "registry:lib") {
                  target = `lib/${fileName}`;
                }
              }

              return {
                path: file.path,
                type: file.type,
                content: sourceFile.getText(),
                target,
              };
            }),
          );
        }

        const payload = registryItemSchema.safeParse({
          ...item,
          files,
        });

        if (payload.success) {
          // Write to public/r/{base}-{name}.json
          await fs.writeFile(
            path.join(REGISTRY_PATH, `${baseName}-${item.name}.json`),
            JSON.stringify(payload.data, null, 2),
            "utf8",
          );
        }
      }
    }
  }
}

try {
  // Validate all registries
  for (const baseName of BASES) {
    const registry = registries[baseName];
    const result = registrySchema.safeParse(registry);

    if (!result.success) {
      console.error(`Error in ${baseName} registry:`, result.error);
      process.exit(1);
    }
  }

  await buildRegistry();
  await buildRegistryJson();
  await buildStyles();

  console.log("✅ Done!");
} catch (error) {
  console.error(error);
  process.exit(1);
}
