/**
 * @see https://github.com/shadcn-ui/ui/blob/main/apps/v4/scripts/build-registry.mts
 */

import { existsSync, promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { cwd } from "node:process";
import { rimraf } from "rimraf";
import { type registryItemTypeSchema, registrySchema } from "shadcn/schema";
import { Project, ScriptKind, SyntaxKind } from "ts-morph";
import type { z } from "zod";
import { DEFAULT_BASE } from "../lib/constants";
import { type RegistryBase, registries } from "../registry/registry";
import { STYLES } from "../registry/styles";

const REGISTRY_PATH = path.join(process.cwd(), "public/r");
const STYLES_PATH = path.join(REGISTRY_PATH, "styles");

// Types included in the per-style public registry.
// registry:example is written only for the default style, not duplicated.
const REGISTRY_INDEX_WHITELIST: z.infer<typeof registryItemTypeSchema>[] = [
  "registry:ui",
  "registry:lib",
  "registry:hook",
  "registry:theme",
  "registry:block",
  "registry:example",
  "registry:component",
  "registry:internal",
  "registry:style",
];

// The style whose output directory receives example JSON files.
const DEFAULT_STYLE = "vega";

const BASES: RegistryBase[] = ["radix", "base"];
const styles = STYLES.map((s) => ({ name: s.name, label: s.title ?? s.name }));

function getStylesToBuild() {
  const stylesToBuild: {
    name: string;
    label: string;
    base: RegistryBase;
    style: { name: string; label: string };
  }[] = [];
  for (const baseName of BASES) {
    for (const style of styles) {
      stylesToBuild.push({
        name: `${baseName}-${style.name}`,
        label: style.label,
        base: baseName,
        style,
      });
    }
  }
  return stylesToBuild;
}

const project = new Project({
  compilerOptions: {},
});

async function createTempSourceFile(filename: string) {
  const dir = await fs.mkdtemp(path.join(tmpdir(), "shadcn-"));
  return path.join(dir, filename);
}

// ----------------------------------------------------------------------------
// Build registry/__index__.ts and examples/__index__.ts.
//
// These are pure METADATA files — no React, no React.lazy, no import() calls.
// Keeping dynamic imports OUT of these files prevents Turbopack from
// statically analyzing thousands of import() paths at build time, which was
// the root cause of OOM. Components are loaded on demand in component-tabs.tsx
// via template-literal dynamic imports instead.
// ----------------------------------------------------------------------------
async function buildRegistry() {
  let index = `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, Record<string, unknown>> = {
`;

  let examplesIndex = `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const ExamplesIndex: Record<string, Record<string, unknown>> = {
`;

  for (const baseName of BASES) {
    const registry = registries[baseName];

    // Add base entry to examples index (examples are keyed by base only, not style)
    examplesIndex += `  "${baseName}": {`;

    for (const style of styles) {
      const styleName = `${baseName}-${style.name}`;
      index += `  "${styleName}": {`;

      // Build style index.
      for (const item of registry.items) {
        const resolveFiles = item.files?.map(
          (file) =>
            `registry/bases/${baseName}/${
              typeof file === "string" ? file : file.path
            }`,
        );
        if (!resolveFiles) {
          continue;
        }

        const type = item.type.split(":")[1];
        let sourceFilename = "";

        let chunks: Array<{
          name: string;
          description: string;
          file: string;
          container: {
            className: string | undefined;
          };
        }> = [];
        if (item.type === "registry:block") {
          const file = resolveFiles[0];
          if (!file) continue;
          const filename = path.basename(file);
          let raw: string;
          try {
            raw = await fs.readFile(file, "utf8");
          } catch (_error) {
            continue;
          }
          const tempFile = await createTempSourceFile(filename);
          const sourceFile = project.createSourceFile(tempFile, raw, {
            scriptKind: ScriptKind.TSX,
          });

          const description = sourceFile
            .getVariableDeclaration("description")
            ?.getInitializerOrThrow()
            .asKindOrThrow(SyntaxKind.StringLiteral)
            .getLiteralValue();

          item.description = description ?? "";

          // Find all imports.
          const imports = new Map<
            string,
            {
              module: string;
              text: string;
              isDefault?: boolean;
            }
          >();
          for (const node of sourceFile.getImportDeclarations()) {
            const module = node.getModuleSpecifier().getLiteralValue();
            for (const importItem of node.getNamedImports()) {
              imports.set(importItem.getText(), {
                module,
                text: node.getText(),
              });
            }

            const defaultImport = node.getDefaultImport();
            if (defaultImport) {
              imports.set(defaultImport.getText(), {
                module,
                text: defaultImport.getText(),
                isDefault: true,
              });
            }
          }

          // Find all opening tags with x-chunk attribute.
          const components = sourceFile
            .getDescendantsOfKind(SyntaxKind.JsxOpeningElement)
            .filter((node) => {
              return node.getAttribute("x-chunk") !== undefined;
            });

          chunks = await Promise.all(
            components.map(async (component, chunkIndex) => {
              const chunkName = `${item.name}-chunk-${chunkIndex}`;

              const attr = component
                .getAttributeOrThrow("x-chunk")
                .asKindOrThrow(SyntaxKind.JsxAttribute);

              const chunkDescription = attr
                .getInitializerOrThrow()
                .asKindOrThrow(SyntaxKind.StringLiteral)
                .getLiteralValue();

              attr.remove();

              component.addAttribute({
                name: "x-chunk",
                initializer: `"${chunkName}"`,
              });

              const containerAttr = component
                .getAttribute("x-chunk-container")
                ?.asKindOrThrow(SyntaxKind.JsxAttribute);

              const containerClassName = containerAttr
                ?.getInitializer()
                ?.asKindOrThrow(SyntaxKind.StringLiteral)
                .getLiteralValue();

              containerAttr?.remove();

              const parentJsxElement = component.getParentIfKindOrThrow(
                SyntaxKind.JsxElement,
              );

              const children = parentJsxElement
                .getDescendantsOfKind(SyntaxKind.JsxOpeningElement)
                .map((node) => node.getTagNameNode().getText())
                .concat(
                  parentJsxElement
                    .getDescendantsOfKind(SyntaxKind.JsxSelfClosingElement)
                    .map((node) => node.getTagNameNode().getText()),
                );

              const componentImports = new Map<
                string,
                string | string[] | Set<string>
              >();
              for (const child of children) {
                const importLine = imports.get(child);
                if (importLine) {
                  const existingImports =
                    componentImports.get(importLine.module) || [];
                  const newImports = importLine.isDefault
                    ? importLine.text
                    : new Set([...existingImports, child]);
                  componentImports.set(
                    importLine.module,
                    importLine?.isDefault ? newImports : Array.from(newImports),
                  );
                }
              }

              const componentImportLines = Array.from(
                componentImports.keys(),
              ).map((key) => {
                const values = componentImports.get(key);
                const specifier = Array.isArray(values)
                  ? `{${values.join(",")}}`
                  : values;
                return `import ${specifier} from "${key}"`;
              });

              const code = `
            'use client'

            ${componentImportLines.join("\n")}

            export default function Component() {
              return (${parentJsxElement.getText()})
            }`;

              const targetFile = file.replace(item.name, `${chunkName}`);
              const targetFilePath = path.join(
                cwd(),
                `registry/bases/${baseName}/${type}/${chunkName}.tsx`,
              );

              rimraf.sync(targetFilePath);
              await fs.writeFile(targetFilePath, code, "utf8");

              return {
                name: chunkName,
                description: chunkDescription,
                file: targetFile,
                container: { className: containerClassName },
              };
            }),
          );

          sourceFilename = `__registry__/${baseName}/${style.name}/${type}/${item.name}.tsx`;

          if (item.files) {
            const files = item.files.map((file) =>
              typeof file === "string"
                ? { type: "registry:page", path: file }
                : file,
            );
            if (files?.length) {
              sourceFilename = `__registry__/${baseName}/${style.name}/${files[0]?.path}`;
            }
          }

          const sourcePath = path.join(process.cwd(), sourceFilename);
          if (!existsSync(sourcePath)) {
            await fs.mkdir(sourcePath, { recursive: true });
          }

          rimraf.sync(sourcePath);
          await fs.writeFile(sourcePath, sourceFile.getText());
        }

        let componentPath = `@/registry/bases/${baseName}/${type}/${item.name}`;

        if (item.files) {
          const files = item.files.map((file) =>
            typeof file === "string"
              ? { type: "registry:page", path: file }
              : file,
          );
          if (files?.length) {
            componentPath = `@/registry/bases/${baseName}/${files[0]?.path}`;
          }
        }

        componentPath = componentPath.replace(/\.(tsx?|jsx?)$/, "");

        const entryStr = `
      "${item.name}": {
        name: "${item.name}",
        description: "${item.description ?? ""}",
        type: "${item.type}",
        registryDependencies: ${JSON.stringify(item.registryDependencies)},
        files: [${item.files?.map((file) => {
          const filePath = `registry/bases/${baseName}/${
            typeof file === "string" ? file : file.path
          }`;
          return typeof file === "string"
            ? `"${filePath}"`
            : `{
          path: "${filePath}",
          type: "${file.type}",
          target: "${file.target ?? ""}"
        }`;
        })}],
        source: "${sourceFilename}",
        chunks: [${chunks.map(
          (chunk) => `{
          name: "${chunk.name}",
          description: "${chunk.description ?? "No description"}",
          file: "${chunk.file}",
          container: {
            className: "${chunk.container.className}"
          }
        }`,
        )}]
      },`;

        if (item.type === "registry:example") {
          if (style === styles[0]) {
            examplesIndex += entryStr;
          }
        } else {
          index += entryStr;
        }
      }

      index += `
    },`;
    }

    examplesIndex += `
  },`;
  }

  index += `
}
`;
  examplesIndex += `
}
`;

  rimraf.sync(path.join(process.cwd(), "registry/__index__.tsx"));
  await fs.writeFile(path.join(process.cwd(), "registry/__index__.tsx"), index);

  await fs.mkdir(path.join(process.cwd(), "examples"), { recursive: true });
  rimraf.sync(path.join(process.cwd(), "examples/__index__.tsx"));
  await fs.writeFile(
    path.join(process.cwd(), "examples/__index__.tsx"),
    examplesIndex,
  );
}

// ----------------------------------------------------------------------------
// Build public/r/styles/{base}-{style}/registry.json and index.json.
// ----------------------------------------------------------------------------
async function buildRegistryJson() {
  const stylesToBuild = getStylesToBuild();

  for (const { name: styleName, base: baseName, style } of stylesToBuild) {
    const registry = registries[baseName];
    const outputDir = path.join(STYLES_PATH, styleName);
    await fs.mkdir(outputDir, { recursive: true });

    const isDefaultStyle = style.name === DEFAULT_STYLE;

    const uiItems = registry.items
      .filter((item) => item.type === "registry:ui")
      .map((item) => ({
        ...item,
        files: item.files?.map((_file) =>
          typeof _file === "string" ? { path: _file, type: item.type } : _file,
        ),
      }));
    await fs.writeFile(
      path.join(outputDir, "index.json"),
      JSON.stringify(uiItems, null, 2),
      "utf8",
    );

    const allItems = registry.items
      .filter((item) => REGISTRY_INDEX_WHITELIST.includes(item.type))
      .filter((item) => item.name !== "index")
      .filter((item) => item.type !== "registry:example" || isDefaultStyle)
      .map((item) => ({
        ...item,
        files: item.files?.map((_file) =>
          typeof _file === "string" ? { path: _file, type: item.type } : _file,
        ),
      }));
    await fs.writeFile(
      path.join(outputDir, "registry.json"),
      JSON.stringify(
        { name: registry.name, homepage: registry.homepage, items: allItems },
        null,
        2,
      ),
      "utf8",
    );
  }
}

// ----------------------------------------------------------------------------
// Build public/r/styles/index.json listing all available styles.
// ----------------------------------------------------------------------------
async function buildStylesIndex() {
  const stylesToBuild = getStylesToBuild();
  const stylesIndex = stylesToBuild.map(({ name, label, base }) => ({
    name,
    label,
    base,
  }));

  await fs.mkdir(STYLES_PATH, { recursive: true });
  await fs.writeFile(
    path.join(STYLES_PATH, "index.json"),
    JSON.stringify(stylesIndex, null, 2),
    "utf8",
  );
}

// ----------------------------------------------------------------------------
// Build public/r/index.json (top-level UI component listing).
// ----------------------------------------------------------------------------
async function buildRootIndex() {
  const registry = registries[DEFAULT_BASE];

  const uiItems = registry.items
    .filter((item) => item.type === "registry:ui")
    .map((item) => {
      // biome-ignore lint/suspicious/noExplicitAny: registry item types vary
      const mapped: Record<string, any> = { name: item.name, type: item.type };
      if (item.dependencies?.length) mapped.dependencies = item.dependencies;
      if (item.registryDependencies?.length)
        mapped.registryDependencies = item.registryDependencies;
      if (item.files) {
        mapped.files = item.files.map((_file) => {
          const file =
            typeof _file === "string"
              ? { path: _file, type: item.type }
              : _file;
          return { path: file.path, type: file.type };
        });
      }
      return mapped;
    });

  await fs.writeFile(
    path.join(REGISTRY_PATH, "index.json"),
    JSON.stringify(uiItems, null, 2),
    "utf8",
  );
}

// ----------------------------------------------------------------------------
// Build public/r/styles/{base}-{style}/{name}.json with inlined file content.
//
// Runs once per base (for DEFAULT_STYLE = "vega"), then copies per-item JSON
// files to the remaining style directories. All style variants are identical
// since visual differences are CSS-variable-based (no source transforms yet).
// ----------------------------------------------------------------------------
async function buildPublicItems() {
  for (const baseName of BASES) {
    const registry = registries[baseName];
    const baseSrcRoot = path.join(process.cwd(), "registry", "bases", baseName);

    // Collect example item names so we can skip copying them to non-default styles
    const exampleFileNames = new Set(
      registry.items
        .filter((item) => item.type === "registry:example")
        .map((item) => `${item.name}.json`),
    );

    // Build all per-item JSON files once, into the default style directory
    const defaultStyleDir = path.join(
      STYLES_PATH,
      `${baseName}-${DEFAULT_STYLE}`,
    );
    await fs.mkdir(defaultStyleDir, { recursive: true });

    for (const item of registry.items) {
      if (!REGISTRY_INDEX_WHITELIST.includes(item.type)) continue;
      if (item.name === "index") continue;

      const files = (
        await Promise.all(
          (item.files ?? []).map(async (_file) => {
            const file =
              typeof _file === "string"
                ? { path: _file, type: item.type, target: "" }
                : _file;

            let content: string;
            try {
              content = await fs.readFile(
                path.join(baseSrcRoot, file.path),
                "utf8",
              );
            } catch {
              return null;
            }

            return {
              path: file.path,
              type: file.type,
              content,
              target: (file as { target?: string }).target ?? "",
            };
          }),
        )
      ).filter(Boolean);

      await fs.writeFile(
        path.join(defaultStyleDir, `${item.name}.json`),
        JSON.stringify({ ...item, files }, null, 2),
        "utf8",
      );
    }

    // Copy per-item JSON files to every other style directory for this base.
    // Skip example files for non-default styles.
    for (const style of styles) {
      if (style.name === DEFAULT_STYLE) continue;

      const styleDir = path.join(STYLES_PATH, `${baseName}-${style.name}`);
      await fs.mkdir(styleDir, { recursive: true });

      const builtFiles = (await fs.readdir(defaultStyleDir)).filter(
        (f) =>
          f.endsWith(".json") &&
          f !== "registry.json" &&
          f !== "index.json" &&
          !exampleFileNames.has(f),
      );

      await Promise.all(
        builtFiles.map((file) =>
          fs.copyFile(
            path.join(defaultStyleDir, file),
            path.join(styleDir, file),
          ),
        ),
      );
    }
  }
}

try {
  const totalStart = performance.now();

  // Validate all registries before touching any output
  for (const baseName of BASES) {
    const result = registrySchema.safeParse(registries[baseName]);
    if (!result.success) {
      console.error(`Error in ${baseName} registry:`, result.error);
      process.exit(1);
    }
  }

  console.log("🧹 Cleaning styles output directory...");
  await rimraf(STYLES_PATH);
  await fs.mkdir(STYLES_PATH, { recursive: true });

  console.log(
    "🏗️  Building registry/__index__.tsx and examples/__index__.tsx...",
  );
  await buildRegistry();

  console.log("📦 Building styles index...");
  await buildStylesIndex();

  console.log("📋 Building public/r/index.json...");
  await buildRootIndex();

  const stylesToBuild = getStylesToBuild();
  console.log(`💅 Building ${stylesToBuild.length} style variants...`);

  // Build per-item JSONs (once per base, then copy across styles)
  await buildPublicItems();

  // Write registry.json + index.json metadata for each style directory.
  // Runs after buildPublicItems so it correctly overwrites anything shadcn may have written.
  await buildRegistryJson();

  for (const style of stylesToBuild) {
    console.log(`   ✅ ${style.name}`);
  }

  const elapsed = ((performance.now() - totalStart) / 1000).toFixed(2);
  console.log(`\n✅ Build complete in ${elapsed}s!`);
} catch (error) {
  console.error(error);
  process.exit(1);
}
