// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "tags-input": {
      name: "tags-input",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/ui/tags-input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/tags-input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "sortable": {
      name: "sortable",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/ui/sortable.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/sortable.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tags-input-demo": {
      name: "tags-input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/example/tags-input-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/tags-input-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tags-input-editable-demo": {
      name: "tags-input-editable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/example/tags-input-editable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/tags-input-editable-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "sortable-demo": {
      name: "sortable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/example/sortable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/sortable-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "sortable-grip-demo": {
      name: "sortable-grip-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","table"],
      files: [{
        path: "registry/default/example/sortable-grip-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/sortable-grip-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      },{
        path: "registry/default/lib/compose-event-handlers.ts",
        type: "registry:lib",
        target: ""
      },{
        path: "registry/default/lib/compose-refs.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
