// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "checkbox-group": {
      name: "checkbox-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/checkbox-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "combobox": {
      name: "combobox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/combobox.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/combobox.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "editable": {
      name: "editable",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/editable.tsx",
        type: "registry:ui",
        target: ""
      },{
        path: "registry/default/components/visually-hidden-input.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/lib/composition.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/editable.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kanban": {
      name: "kanban",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/kanban.tsx",
        type: "registry:ui",
        target: ""
      },{
        path: "registry/default/lib/composition.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/kanban.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd": {
      name: "kbd",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/kbd.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/kbd.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "listbox": {
      name: "listbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/listbox.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/listbox.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "masonry": {
      name: "masonry",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/masonry.tsx",
        type: "registry:ui",
        target: ""
      },{
        path: "registry/default/lib/composition.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/masonry.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "mention": {
      name: "mention",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/mention.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/mention.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "relative-time-card": {
      name: "relative-time-card",
      description: "",
      type: "registry:ui",
      registryDependencies: ["hover-card"],
      files: [{
        path: "registry/default/ui/relative-time-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/relative-time-card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "scroller": {
      name: "scroller",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/scroller.tsx",
        type: "registry:ui",
        target: ""
      },{
        path: "registry/default/lib/composition.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/scroller.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "sortable": {
      name: "sortable",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/sortable.tsx",
        type: "registry:ui",
        target: ""
      },{
        path: "registry/default/lib/composition.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/sortable.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tags-input": {
      name: "tags-input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tags-input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/tags-input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "composition": {
      name: "composition",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/composition.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/composition.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-group-demo": {
      name: "checkbox-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/checkbox-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-group-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-group-animated-demo": {
      name: "checkbox-group-animated-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/checkbox-group-animated-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-group-animated-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-group-horizontal-demo": {
      name: "checkbox-group-horizontal-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/checkbox-group-horizontal-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-group-horizontal-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-group-validation-demo": {
      name: "checkbox-group-validation-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/checkbox-group-validation-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-group-validation-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-group-multi-selection-demo": {
      name: "checkbox-group-multi-selection-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/checkbox-group-multi-selection-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-group-multi-selection-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "combobox-demo": {
      name: "combobox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["combobox"],
      files: [{
        path: "registry/default/examples/combobox-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/combobox-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "combobox-groups-demo": {
      name: "combobox-groups-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["combobox"],
      files: [{
        path: "registry/default/examples/combobox-groups-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/combobox-groups-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "combobox-multiple-demo": {
      name: "combobox-multiple-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["combobox"],
      files: [{
        path: "registry/default/examples/combobox-multiple-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/combobox-multiple-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "combobox-custom-filter-demo": {
      name: "combobox-custom-filter-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["combobox"],
      files: [{
        path: "registry/default/examples/combobox-custom-filter-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/combobox-custom-filter-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "combobox-debounced-demo": {
      name: "combobox-debounced-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["combobox"],
      files: [{
        path: "registry/default/examples/combobox-debounced-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/combobox-debounced-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "combobox-virtualized-demo": {
      name: "combobox-virtualized-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["combobox"],
      files: [{
        path: "registry/default/examples/combobox-virtualized-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/combobox-virtualized-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "combobox-tags-demo": {
      name: "combobox-tags-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["combobox","tags-input"],
      files: [{
        path: "registry/default/examples/combobox-tags-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/combobox-tags-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "editable-demo": {
      name: "editable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/editable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/editable-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "editable-double-click-demo": {
      name: "editable-double-click-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/editable-double-click-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/editable-double-click-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "editable-autosize-demo": {
      name: "editable-autosize-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/editable-autosize-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/editable-autosize-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "editable-todo-list-demo": {
      name: "editable-todo-list-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["checkbox","button"],
      files: [{
        path: "registry/default/examples/editable-todo-list-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/editable-todo-list-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "editable-form-demo": {
      name: "editable-form-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","form"],
      files: [{
        path: "registry/default/examples/editable-form-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/editable-form-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kanban-demo": {
      name: "kanban-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["badge","button"],
      files: [{
        path: "registry/default/examples/kanban-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kanban-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kanban-dynamic-overlay-demo": {
      name: "kanban-dynamic-overlay-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["badge","button"],
      files: [{
        path: "registry/default/examples/kanban-dynamic-overlay-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kanban-dynamic-overlay-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd-demo": {
      name: "kbd-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/kbd-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kbd-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd-variants-demo": {
      name: "kbd-variants-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/kbd-variants-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kbd-variants-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd-multiple-demo": {
      name: "kbd-multiple-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/kbd-multiple-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kbd-multiple-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "listbox-demo": {
      name: "listbox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/listbox-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/listbox-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "listbox-horizontal-demo": {
      name: "listbox-horizontal-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/listbox-horizontal-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/listbox-horizontal-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "listbox-grid-demo": {
      name: "listbox-grid-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/listbox-grid-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/listbox-grid-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "listbox-group-demo": {
      name: "listbox-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/listbox-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/listbox-group-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "masonry-demo": {
      name: "masonry-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/masonry-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/masonry-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "masonry-linear-demo": {
      name: "masonry-linear-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["skeleton"],
      files: [{
        path: "registry/default/examples/masonry-linear-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/masonry-linear-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "masonry-ssr-demo": {
      name: "masonry-ssr-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["skeleton"],
      files: [{
        path: "registry/default/examples/masonry-ssr-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/masonry-ssr-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "mention-demo": {
      name: "mention-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["mention"],
      files: [{
        path: "registry/default/examples/mention-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/mention-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "mention-custom-filter-demo": {
      name: "mention-custom-filter-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["mention"],
      files: [{
        path: "registry/default/examples/mention-custom-filter-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/mention-custom-filter-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "mention-custom-trigger-demo": {
      name: "mention-custom-trigger-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["mention"],
      files: [{
        path: "registry/default/examples/mention-custom-trigger-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/mention-custom-trigger-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "relative-time-card-demo": {
      name: "relative-time-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","hover-card"],
      files: [{
        path: "registry/default/examples/relative-time-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/relative-time-card-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "relative-time-card-variants-demo": {
      name: "relative-time-card-variants-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","hover-card"],
      files: [{
        path: "registry/default/examples/relative-time-card-variants-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/relative-time-card-variants-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "relative-time-card-timezones-demo": {
      name: "relative-time-card-timezones-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["hover-card"],
      files: [{
        path: "registry/default/examples/relative-time-card-timezones-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/relative-time-card-timezones-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "scroller-demo": {
      name: "scroller-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/scroller-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroller-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "scroller-horizontal-demo": {
      name: "scroller-horizontal-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/scroller-horizontal-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroller-horizontal-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "scroller-hidden-demo": {
      name: "scroller-hidden-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/scroller-hidden-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroller-hidden-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "scroller-navigation-demo": {
      name: "scroller-navigation-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/scroller-navigation-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroller-navigation-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "sortable-demo": {
      name: "sortable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/sortable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/sortable-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "sortable-dynamic-overlay-demo": {
      name: "sortable-dynamic-overlay-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/sortable-dynamic-overlay-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/sortable-dynamic-overlay-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "sortable-primitive-values-demo": {
      name: "sortable-primitive-values-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/sortable-primitive-values-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/sortable-primitive-values-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "sortable-handle-demo": {
      name: "sortable-handle-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","table"],
      files: [{
        path: "registry/default/examples/sortable-handle-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/sortable-handle-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tags-input-demo": {
      name: "tags-input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/tags-input-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/tags-input-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tags-input-editable-demo": {
      name: "tags-input-editable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tags-input","button"],
      files: [{
        path: "registry/default/examples/tags-input-editable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/tags-input-editable-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tags-input-sortable-demo": {
      name: "tags-input-sortable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tags-input","sortable","button"],
      files: [{
        path: "registry/default/examples/tags-input-sortable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/tags-input-sortable-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tags-input-validation-demo": {
      name: "tags-input-validation-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tags-input","button"],
      files: [{
        path: "registry/default/examples/tags-input-validation-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/tags-input-validation-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "client-only": {
      name: "client-only",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/client-only.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/client-only.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "direction-provider": {
      name: "direction-provider",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/direction-provider.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/direction-provider.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "portal": {
      name: "portal",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/portal.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/portal.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "visually-hidden": {
      name: "visually-hidden",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/visually-hidden.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/visually-hidden.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "visually-hidden-input": {
      name: "visually-hidden-input",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/visually-hidden-input.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/visually-hidden-input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
